INSERT INTO car_types (name) Values ('Sedan')
INSERT INTO car_types (name) Values ('Coupe')
INSERT INTO car_types (name) Values ('Station Wagon')
INSERT INTO car_types (name) Values ('Convertible')
INSERT INTO car_types (name) Values ('Sport Car')
INSERT INTO car_types (name) Values ('Mini-van')
INSERT INTO car_types (name) Values ('SUV')
INSERT INTO car_types (name) Values ('Pickup Truck')
INSERT INTO car_types (name) Values ('Van')
